version: "3.9"

services:
  timescaledb:
    container_name: timescaledb
    build:
      context: .
      dockerfile: Dockerfile.timescaledb
    image: local/timescaledb-pgvector:pg16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescaledb_data:
